CREATE TABLE IF NOT EXISTS player (playerId BIGINT PRIMARY KEY, playerName VARCHAR(255));
CREATE TABLE IF NOT EXISTS account (accountNumber BIGINT PRIMARY KEY, balance DOUBLE PRECISION, playerId BIGINT);
CREATE TABLE IF NOT EXISTS transaction_history (transactionId VARCHAR(20) PRIMARY KEY, amount DOUBLE PRECISION, accountNumber BIGINT, updateDtime TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS player_seq AS INTEGER START WITH 10;
CREATE SEQUENCE IF NOT EXISTS account_seq AS INTEGER START WITH 1000;